/*
Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair of elements from the array.
Note: AND is bitwise '&' operator.

Example 1:

Input : Arr[] = {4, 8, 12, 16}
Output : 8

Explanation:
Pair (8,12) has the Maximum AND Value
i.e. 8.

Example 2:

Input : Arr[] = {4, 8, 16, 2} 
Output : 0

Your Task:
The input is already taken care of by the driver code. You only need to complete the function maxAND() that takes an array (arr), size of Array (n) as parameter and return the maximum AND value of pair. The driver code takes care of the printing.
*/
let arr = [4, 8, 12, 16];
let n = 4;
let max = -1;
if(n==1){
    console.log(0);
}
arr.sort((a,b)=>a-b); //2 4 8 16 // 4 8 12 16
for(let i=n-1;i>=0;i--){
    if(i>0){
        max = Math.max(max, arr[i]&arr[i-1]);
    }
}
console.log(max);

/*
class Solution {   
    maxAND(arr,n)
    {
        //your code here
        let max=-1;
        if(n==1){
            return 0;
        }
        arr.sort((a,b)=>a-b);
        for(let i=n-1;i>=0;i--){
            if(i>0){
                max=Math.max(max,(arr[i]&arr[i-1]))
            }
        }
        return max;
    }
}
*/